---
# tasks install for ansible-role-logrotate

- name: Update apt cache on Debian Family os
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Update emerge cache on Gentoo
  command: emerge-webrsync
  changed_when: false
  when: ansible_os_family == "Gentoo"

- name: install logrotate
  package:
    name: "{{ logrotate_package }}"
    state: present
