name: CI

on:
  push:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - centos-9
          - centos-8
          - centos-7

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Docker build
        run: |
          docker run -d diodonfrost/${{ matrix.distribution }}-ansible:latest

          docker ps -a

      - name: Docker ls
        run: |
          docker ps -a
