name: galaxy

on:
  push:
    tags:
    - '*'

jobs:
  release:
    name: Test creds
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test run
        run: |
          ifconig -a
          pwd
          ls -l
