name: galaxy

on: [push, pull_request]

jobs:
  release:
    name: Test creds
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Test run
        run: |
          pwd
          ls -l
          echo "-------------------------------"
          echo "test secret: $test_secret"
          if [ "$test_secret" = "Thisisatest" ]; then
              echo "Strings are equal."
          else
              echo "Strings are not equal."
          fi
          echo "-------------------------------"
        env:
          test_secret: ${{ secrets.TEST_SECRET }}
