name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        - distribution: centos-8
          playbook: java-latest
        - distribution: centos-8
          playbook: java-11
        - distribution: centos-8
          playbook: java-8
        - distribution: centos-7
          playbook: java-latest
        - distribution: centos-7
          playbook: java-8
        - distribution: centos-7
          playbook: java-7
        - distribution: centos-7
          playbook: java-6
        - distribution: centos-6
          playbook: java-latest
        - distribution: centos-6
          playbook: java-8
        - distribution: centos-6
          playbook: java-7
        - distribution: centos-6
          playbook: java-6
      
      #--------------------------------
      #
      # Fedora
      #
      #--------------------------------
        - distribution: fedora-32
          playbook: java-latest
        - distribution: fedora-32
          playbook: java-13
        - distribution: fedora-32
          playbook: java-11
        - distribution: fedora-32
          playbook: java-8
        - distribution: fedora-31
          playbook: java-latest
        - distribution: fedora-31
          playbook: java-13
        - distribution: fedora-31
          playbook: java-11
        - distribution: fedora-31
          playbook: java-8
        - distribution: fedora-30
          playbook: java-latest
        - distribution: fedora-30
          playbook: java-12
        - distribution: fedora-30
          playbook: java-11
        - distribution: fedora-30
          playbook: java-8
        - distribution: fedora-29
          playbook: java-latest
        - distribution: fedora-29
          playbook: java-11
        - distribution: fedora-29
          playbook: java-8
        - distribution: fedora-28
          playbook: java-latest
        - distribution: fedora-28
          playbook: java-11
        - distribution: fedora-28
          playbook: java-8
        - distribution: fedora-27
          playbook: java-latest
        - distribution: fedora-27
          playbook: java-11
        - distribution: fedora-27
          playbook: java-9
        - distribution: fedora-27
          playbook: java-8
        - distribution: fedora-26
          playbook: java-latest
        - distribution: fedora-26
          playbook: java-9
        - distribution: fedora-26
          playbook: java-8
      
      #--------------------------------
      #
      # Ubuntu
      #
      #--------------------------------
        - distribution: ubuntu-20.04
          playbook: java-latest
        - distribution: ubuntu-20.04
          playbook: java-11
        - distribution: ubuntu-20.04
          playbook: java-8
        - distribution: ubuntu-18.04
          playbook: java-latest
        - distribution: ubuntu-18.04
          playbook: java-11
        - distribution: ubuntu-18.04
          playbook: java-8
        - distribution: ubuntu-16.04
          playbook: java-latest
        - distribution: ubuntu-16.04
          playbook: java-9
        - distribution: ubuntu-16.04
          playbook: java-8
        - distribution: ubuntu-14.04
          playbook: java-latest
        - distribution: ubuntu-14.04
          playbook: java-7
        - distribution: ubuntu-14.04
          playbook: java-6
        - distribution: ubuntu-12.04
          playbook: java-latest
        - distribution: ubuntu-12.04
          playbook: java-7
        - distribution: ubuntu-12.04
          playbook: java-6
      
      #--------------------------------
      #
      # Debian
      #
      #--------------------------------
        - distribution: debian-10
          playbook: java-latest
        - distribution: debian-10
          playbook: java-11
        - distribution: debian-9
          playbook: java-latest
        - distribution: debian-9
          playbook: java-8
        - distribution: debian-8
          playbook: java-latest
        - distribution: debian-8
          playbook: java-7
      
      #--------------------------------
      #
      # Oraclelinux
      #
      #--------------------------------
        - distribution: oraclelinux-8
          playbook: java-latest
        - distribution: oraclelinux-8
          playbook: java-11
        - distribution: oraclelinux-8
          playbook: java-8
        - distribution: oraclelinux-7
          playbook: java-latest
        - distribution: oraclelinux-7
          playbook: java-11
        - distribution: oraclelinux-7
          playbook: java-8
        - distribution: oraclelinux-7
          playbook: java-7
        - distribution: oraclelinux-7
          playbook: java-6
        - distribution: oraclelinux-6
          playbook: java-latest
        - distribution: oraclelinux-6
          playbook: java-8
        - distribution: oraclelinux-6
          playbook: java-7
        - distribution: oraclelinux-6
          playbook: java-6
      
      #--------------------------------
      #
      # Amazonlinux
      #
      #--------------------------------
        - distribution: amazonlinux-2
          playbook: java-latest
        - distribution: amazonlinux-2
          playbook: java-8
        - distribution: amazonlinux-2
          playbook: java-7
        - distribution: amazonlinux-1
          playbook: java-latest
        - distribution: amazonlinux-1
          playbook: java-8
        - distribution: amazonlinux-1
          playbook: java-7
        - distribution: amazonlinux-1
          playbook: java-6
      
      #--------------------------------
      #
      # Opensuse
      #
      #--------------------------------
        - distribution: opensuse-15.1
          playbook: java-latest
        - distribution: opensuse-15.1
          playbook: java-11
        - distribution: opensuse-15.1
          playbook: java-10
        - distribution: opensuse-15.1
          playbook: java-8
        - distribution: opensuse-15
          playbook: java-latest
        - distribution: opensuse-15
          playbook: java-11
        - distribution: opensuse-15
          playbook: java-10
        - distribution: opensuse-15
          playbook: java-8
        - distribution: opensuse-42.3
          playbook: java-latest
        - distribution: opensuse-42.3
          playbook: java-8
        - distribution: opensuse-42.3
          playbook: java-7
        - distribution: opensuse-13.2
          playbook: java-latest
        - distribution: opensuse-13.2
          playbook: java-8
        - distribution: opensuse-13.2
          playbook: java-7
      
      #--------------------------------
      #
      # Archlinux
      #
      #--------------------------------
        - distribution: archlinux-rolling
          playbook: java-latest
        - distribution: archlinux-rolling
          playbook: java-11
        - distribution: archlinux-rolling
          playbook: java-10
        - distribution: archlinux-rolling
          playbook: java-8
        - distribution: archlinux-rolling
          playbook: java-7
      
      #--------------------------------
      #
      # Alpine
      #
      #--------------------------------
        - distribution: alpine-rolling
          playbook: java-latest
        - distribution: alpine-rolling
          playbook: java-8
        - distribution: alpine-rolling
          playbook: java-7

    steps:
    - uses: actions/checkout@v2

    - name: yarn install, yarn lint, yarn test, yarn build
      run: |
        container_id=$(mktemp)
        sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/ansible-role-java:ro diodonfrost/${{ matrix.distribution }}-ansible:latest > "${container_id}"
        sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-java/tests/playbooks/${{ matrix.playbook }}.yml --syntax-check
        sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-java/tests/playbooks/${{ matrix.playbook }}.yml
        sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/ansible-role-java/tests/playbooks/${{ matrix.playbook }}.yml | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        inspec exec tests/inspec --chef-license accept-silent -t docker://$(cat ${container_id})
